In [1]:
from ml_models import model_loading
import torch
from torch.nn.functional import softplus
import gz21_ocean_momentum.models.transforms as transforms

To load the net from the paper, use the function load_paper_net().
CUDA Not Available


In [11]:
net = model_loading()
net.final_transformation

SoftPlusTransform(Parameter containing:
tensor(0.0015, requires_grad=True))

In [4]:
test = torch.randn(5, 4, 100, 100)

In [10]:
net.final_transformation(test).mean(axis=(0, 2, 3))

tensor([0.0022, 0.0011, 0.8069, 0.8109], grad_fn=<MeanBackward1>)

In [17]:
min_value, precision_indices = 0.0015, [2,3]
out_sf = test.clone()
out_sf[:, precision_indices] = softplus(test[:, precision_indices]) + min_value
out_sf.mean(axis=(0, 2, 3))

tensor([0.0022, 0.0011, 0.8069, 0.8109])

In [19]:
min_value, precision_indices = 0.0015, [2,3]
out_sf = test.clone()
out_sf[:, precision_indices] = softplus(test[:, precision_indices]) + softplus(torch.tensor(min_value))
out_sf.mean(axis=(0, 2, 3))

tensor([2.2020e-03, 1.1036e-03, 1.4993e+00, 1.5033e+00])